language: node_js
node_js:
  - "8.10.0"

before_install:
  - npm config set loglevel info --global

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm i

script:
  - npm run ci
