language: node_js
node_js:
  - lts/*
  - 14
  - 12

addons:
    apt:
        packages:
            - xvfb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm i

script:
  - npm run lint
  - npm test
  - ./node_modules/.bin/codecov
